# -*- coding: utf-8 -*-
"""testingnotebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_dKro9NgqFP5saWw8-IIseEDYUrbutQ4
"""
'''!pip install ultralytics'''
from ultralytics import YOLO
import matplotlib.pyplot as plt

# Loading our Pretrained Model
model = YOLO("/Users/adithyasarma/Desktop/Pharaoh-Finder/AI/75EpochModel/ModelWeights/best.pt")

# Path to Testing Image
image_path = "/Users/adithyasarma/Desktop/testimages/a400m-anubis.jpg"

# Running the model with image
results = model(image_path)
result = results[0]

# Getting the annotated image and displaying it using matplotlib
annotated_img = result.plot()
plt.figure(figsize=(8, 8))
plt.imshow(annotated_img)
plt.axis('off')
plt.show()