# -*- coding: utf-8 -*-
"""trainingnotebook.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tx4YzBrENKqKIt8sQwbXil47vSfeU2cU
"""
'''!pip install kaggle ultralytics torch torchvision opencv-python --quiet'''

import torch
print("CUDA available:", torch.cuda.is_available())
print("CUDA device count:", torch.cuda.device_count())
if torch.cuda.is_available():
    for i in range(torch.cuda.device_count()):
        print(f"Device {i}: {torch.cuda.get_device_name(i)}")

import os
print(os.path.exists("/kaggle/input/mydataset/dataset/val/images"))

input_dataset = "/kaggle/input/mydataset/dataset"  # Original dataset (read-only)
working_dataset = "/kaggle/input/mydataset/dataset"

yaml_content = f"""
path: {working_dataset}
train: train/images
val: val/images
test: test/images

names:
  0: Horus
  1: Osiris
  2: Anubis
  3: Ra

nc: 4
"""

with open("/kaggle/working/data.yaml", "w") as f:
    f.write(yaml_content)

print("data.yaml created!")

from ultralytics import YOLO

# Load the YOLO8 model (nano version)
model = YOLO("yolov8n.pt")

# Training model with out custom data
model.train(
    data="/kaggle/working/data.yaml",
    epochs=100,
    imgsz=640,
    batch=32,
    device="auto",
    half=True,
    project="/kaggle/working/results",
    name="aircraft_detection_new"
)